on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

name: Integration tests

env:
  REGISTRY: localhost:32000
  IMAGE_NAME: ${{ github.repository }}

jobs:
  microk8s:
    name: Set-up MicroK8s single node instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set-up microk8s instance with registry
        uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: 'latest/stable'
          addons: '["registry"]'

      - name: Test MicroK8s
        id: myactions
        run: |
          kubectl get no
          kubectl get pods -A -o wide

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          flavor: |
            latest=true
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
